# -*- coding: utf-8 -*-
"""Mining Twitter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iQCe5yBm-SLHUs-TXOjl9tDlaqcVGksi
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive')
# %cd /content/gdrive/My\ Drive/miningtwitter/

import tweepy
from tweepy import OAuthHandler
from tweepy import Stream
from tweepy.streaming import StreamListener
import json
import datetime
import time

consumer_key = 'o3i1Qekv7q5ieJRChTzoDXctj'
consumer_secret = 'mTm5h4t06ea8uvtTmtYEB7kgKbaVnmLMtX7Awp8m3h4NSGUF5i'
access_token = '1366906723-GmgKb0Rxc7lV2Dt6pQAFhgxaPGLmKCvi5EzdGZI'
access_secret = 'LH0ymkGUXUhv8MZyiXNd1qgYmeRiE4I8kXVr6Jtd1zUpX'

auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
 
api = tweepy.API(auth)

hitung = 0
print("Memulai proses data mining tweet...\n")

class MyListener(StreamListener):
	def on_data(self, data):
		try:
			global hitung
			with open('datamining.csv','a') as datanya:		
				hitung = hitung + 1
				print("Jumlah data terekam : ",str(hitung), " \n")
				datanya.write(data)
				return True
		except BaseException as masalah:
			print("Error pada data : %s" % str(masalah))
		return True
		def on_error(self, status):
			print(status)
			return True

twitter_stream = Stream(auth, MyListener())
twitter_stream.filter(track=['@halodoc','@alodokter_id','@klikdoktercom','#konsultasionline',
                             '#halodoc','#alodokter','#klikdokter'])

import os
totalSize = 0
totalSize += os.path.getsize('/content/gdrive/My Drive/miningtwitter/miningtweet.csv')
print('Size : {:,} MB'.format(int(totalSize/1000**2)).replace(',',''))
print('Size : {:,} GB'.format(int(totalSize/1000**3)).replace(',',''))